server:
  port: ${PORT}
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: freelavalink.ga
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 100
    youtubePlaylistLoadLimit: 30
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""

  level:
    root: INFO
    lavalink: INFO
